name: VOIDGAME
version: '${project.version}'
main: me.krokodil69u.voidgame.VOIDGAME
api-version: '1.20'
commands:
  start:
    usage: /start
  vgstop:
    usage: /stop
  startevent:
    usage: /startevent